[phases.setup]
nixPkgs = ['python39', 'nodejs-18_x']

[phases.install]
cmds = [
    'cd backend && pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'cd backend && python app.py'
