[providers]
type = "python"

[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Python Flask app ready"']

[start]
cmd = 'python app.py'
