[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "querybox-frontend"
source = "frontend"
variables = { NODE_ENV = "production" }

[[services]]  
name = "querybox-backend"
source = "backend"
variables = { FLASK_ENV = "production", PORT = "5000" }
